/** dsh-dev-memory polished settings panel + conversation memory cards — static CJS client bundle. */
const CSS = [
'.dm-panel{padding:16px;line-height:1.5;color:inherit}',
'.dm-card{border:1px solid var(--dsw-alias-border-primary,rgba(127,127,127,.22));border-radius:14px;padding:16px;margin-bottom:14px;background:var(--dsw-alias-bg-secondary,rgba(127,127,127,.045));box-shadow:0 1px 2px rgba(0,0,0,.04)}',
'.dm-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}',
'.dm-title-wrap{display:flex;align-items:center;gap:9px;min-width:0}.dm-title{font-size:15px;font-weight:700}.dm-subtitle{font-size:12px;color:var(--dsw-alias-label-secondary,#888)}',
'.dm-status-dot{width:9px;height:9px;border-radius:50%;background:#999;box-shadow:0 0 0 3px rgba(127,127,127,.12);flex:none}.dm-status-dot.on{background:#21c765;box-shadow:0 0 0 3px rgba(33,199,101,.14)}.dm-status-dot.warn{background:#f1a72c;box-shadow:0 0 0 3px rgba(241,167,44,.14)}',
'.dm-grid{display:grid;grid-template-columns:minmax(112px,145px) minmax(0,1fr);gap:9px 12px;align-items:start}.dm-label{font-size:12px;font-weight:700;color:var(--dsw-alias-label-secondary,#777)}.dm-value{font-size:13px;min-width:0;word-break:break-all}',
'.dm-path-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.dm-input{flex:1;min-width:210px;padding:7px 10px;border:1px solid var(--dsw-alias-border-primary,#aaa);border-radius:7px;background:var(--dsw-alias-bg-primary,transparent);color:inherit;outline:none;transition:border-color .15s,box-shadow .15s}.dm-input:focus{border-color:#3c8cff;box-shadow:0 0 0 3px rgba(60,140,255,.14)}',
'.dm-button{appearance:none;border:1px solid var(--dsw-alias-border-primary,#aaa);border-radius:8px;padding:6px 12px;background:var(--dsw-alias-bg-primary,transparent);color:inherit;font-size:12px;font-weight:600;cursor:pointer;transition:background .14s,border-color .14s,transform .08s,box-shadow .14s}.dm-button:hover:not(:disabled){background:rgba(60,140,255,.1);border-color:#3c8cff;box-shadow:0 2px 8px rgba(0,0,0,.08)}.dm-button:active:not(:disabled){transform:scale(.96);box-shadow:none}.dm-button:disabled{opacity:.48;cursor:not-allowed}.dm-button.primary{background:#287be6;border-color:#287be6;color:#fff}',
'.dm-feedback{font-size:12px;font-weight:600;min-height:18px;margin-top:8px}.dm-feedback.ok{color:#159b4b}.dm-feedback.error{color:#d34b4b}',
'.dm-switch{position:relative;display:inline-flex;width:38px;height:22px;cursor:pointer;flex:none}.dm-switch input{position:absolute;opacity:0}.dm-switch-track{position:absolute;inset:0;border-radius:99px;background:#aaa;transition:.18s}.dm-switch-knob{position:absolute;width:18px;height:18px;left:2px;top:2px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.28);transition:transform .18s}.dm-switch input:checked~.dm-switch-track{background:#20bd61}.dm-switch input:checked~.dm-switch-knob{transform:translateX(16px)}.dm-switch:hover .dm-switch-track{box-shadow:0 0 0 3px rgba(33,199,101,.12)}',
'.dm-stat-row{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:11px}.dm-stat{padding:9px 10px;border-radius:9px;background:rgba(127,127,127,.075)}.dm-stat-name{font-size:11px;color:var(--dsw-alias-label-secondary,#888)}.dm-stat-value{font-size:15px;font-weight:700}',
'.dm-issues,.dm-changes{display:flex;flex-direction:column;gap:8px}.dm-issue{padding:9px 10px;border-left:3px solid #e4a02a;border-radius:6px;background:rgba(228,160,42,.075)}.dm-issue-title{font-size:12px;font-weight:700}.dm-issue-files,.dm-empty{font-size:11px;color:var(--dsw-alias-label-secondary,#888);margin-top:3px;word-break:break-word}',
'.dm-change{padding:11px 12px 11px 14px;border:1px solid var(--dsw-alias-border-primary,rgba(127,127,127,.18));border-radius:10px;background:var(--dsw-alias-bg-primary,transparent)}.dm-change.latest{border-left:4px solid #21c765;background:rgba(33,199,101,.045)}.dm-change-top,.dm-change-meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.dm-action{font-size:11px;font-weight:700;padding:2px 7px;border-radius:99px}.dm-action.create{color:#128b43;background:rgba(33,199,101,.13)}.dm-action.update{color:#2673d6;background:rgba(60,140,255,.13)}.dm-action.write{color:inherit;background:rgba(127,127,127,.12)}.dm-file{font-size:12px;font-weight:700;word-break:break-all}.dm-summary{font-size:12px;margin-top:5px}.dm-change-meta{margin-top:6px;font-size:11px;color:var(--dsw-alias-label-secondary,#888)}.dm-tag{padding:1px 6px;border-radius:99px;background:rgba(127,127,127,.1)}.change-time{font-variant-numeric:tabular-nums}',
'.dm-ws-list{display:flex;flex-direction:column;gap:6px;max-height:220px;overflow:auto;margin-top:8px}.dm-ws-item{text-align:left;border:1px solid var(--dsw-alias-border-primary,rgba(127,127,127,.18));border-radius:10px;padding:8px 10px;background:transparent;color:inherit;cursor:pointer}.dm-ws-item.active{border-color:#21c765;background:rgba(33,199,101,.06)}.dm-ws-name{font-size:13px;font-weight:700}.dm-ws-path{font-size:11px;color:var(--dsw-alias-label-secondary,#888);word-break:break-all}',
'.dm-tool{border:1px solid var(--dsw-alias-border-primary,rgba(127,127,127,.18));border-radius:10px;padding:8px 10px;background:var(--dsw-alias-bg-secondary,rgba(127,127,127,.04));font-size:12px}.dm-tool summary{cursor:pointer;font-weight:700}.dm-tail{margin-top:8px;padding:8px 10px;border-radius:10px;background:rgba(33,199,101,.08);font-size:12px}',
'.dm-composer-toggle{display:inline-flex;align-items:center;gap:6px;height:22px;padding:0 4px;font-size:12px;font-weight:600;white-space:nowrap;color:inherit;cursor:pointer;user-select:none}',
'.dm-writepass{box-sizing:border-box;display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;max-width:var(--dsh-composer-card-max-width,780px);margin:0 auto;padding:8px 12px;border-radius:12px;background:rgba(60,140,255,.1);font-size:12px;font-weight:600}',
'@media(max-width:640px){.dm-grid{grid-template-columns:1fr}.dm-stat-row{grid-template-columns:repeat(2,minmax(0,1fr))}.dm-input{min-width:160px}}'
].join('');

const ISSUE_LABELS={missingReadmeDirs:'缺少目录索引',overlongFiles:'文件过长',missingMeta:'缺少元数据',missingQuickJudgment:'缺少快速判断',missingAssociatedMemory:'缺少关联记忆',missingPendingVerification:'缺少待验证项',oldLineTables:'旧格式行号表',pendingEntrypoints:'待补入口',brokenLinks:'失效链接',duplicateLinks:'重复链接',sameNameMdAndDir:'文档与目录重名',bomFiles:'BOM 文件',replacementCharFiles:'异常替换字符'};
function formatIssueValue(v){if(v==null)return'';if(typeof v!=='object')return String(v);const p=v.file||v.path||v.relPath||v.dir||v.module||'';const d=v.meta||v.reason||v.message||v.issue||'';if(p&&d)return String(p)+' — '+String(d);if(p||d)return String(p||d);try{return JSON.stringify(v)}catch{return String(v)}}
function actionPresentation(a){if(a==='create')return{icon:'+',label:'新增',tone:'create'};if(a==='update')return{icon:'✎',label:'更新',tone:'update'};return{icon:'•',label:'写入',tone:'write'}}
function pad2(v){return String(v).padStart(2,'0')}
function formatLocalTime(ts,offset){const n=Number(ts);if(!Number.isFinite(n))return'';const x=Number.isFinite(offset),d=new Date(x?n-offset*60000:n);const g=x?'getUTC':'get';return d[g+'FullYear']()+'-'+pad2(d[g+'Month']()+1)+'-'+pad2(d[g+'Date']())+' '+pad2(d[g+'Hours']())+':'+pad2(d[g+'Minutes']())+':'+pad2(d[g+'Seconds']())}
function formatRelativeTime(ts,now){const diff=Math.max(0,Number(now==null?Date.now():now)-Number(ts));if(!Number.isFinite(diff)||diff<60000)return'刚刚';const m=Math.floor(diff/60000);if(m<60)return m+' 分钟前';const h=Math.floor(m/60);if(h<24)return h+' 小时前';return Math.floor(h/24)+' 天前'}
function parseJson(text){if(!text)return null;try{return JSON.parse(text)}catch{return null}}
function blockArgs(block){const raw=block&&('kind' in block?block.call&&block.call.argsRaw:block.argsRaw);return parseJson(raw)||{}}
function blockOutput(block){if(!block||!('kind' in block))return null;if(typeof block.output==='string')return parseJson(block.output);const text=block.result&&block.result.content&&block.result.content[0]&&block.result.content[0].text;return parseJson(text)}
function filterWorkspaces(rows,query){const list=Array.isArray(rows)?rows:[];const q=String(query||'').trim().toLowerCase();if(!q)return list;return list.filter(row=>[row.id,row.name,row.workspacePath,row.memoryRoot].some(v=>String(v||'').toLowerCase().includes(q)))}
function sameMemoryRoot(a,b){return String(a||'').replace(/[\\/]+$/,'')===String(b||'').replace(/[\\/]+$/,'')}
function normalizeSlugId(id){return String(id||'').replace(/_/g,'-')}
function mergeWorkspaceRows(rows){const list=Array.isArray(rows)?rows:[];const out=[];for(const row of list){if(!row||!row.id)continue;const id=normalizeSlugId(row.id);const match=out.find(x=>normalizeSlugId(x.id)===id||(row.memoryRoot&&x.memoryRoot&&sameMemoryRoot(x.memoryRoot,row.memoryRoot)));if(!match){out.push({...row,id});continue}if(row.verified&&!match.verified){match.id=id;match.name=row.name||match.name;match.verified=true;match.workspacePath=row.workspacePath||match.workspacePath;match.memoryRoot=row.memoryRoot||match.memoryRoot;match.pinned=!!row.pinned||!!match.pinned;continue}match.id=id.includes('_')?match.id:id;if(!match.workspacePath&&row.workspacePath)match.workspacePath=row.workspacePath;if(row.verified){match.verified=true;match.workspacePath=row.workspacePath||match.workspacePath}if(!match.memoryRoot&&row.memoryRoot)match.memoryRoot=row.memoryRoot;if(row.pinned)match.pinned=true}return out}
function workspaceStatusLabel(row,activeId){if(!row)return'';if(activeId&&row.id===activeId)return'当前会话';if(row.verified)return'已绑定工作目录';return'仅发现记忆库'}
function browseStateUrl(id){return id?'/dsh-dev-memory/state?workspace='+encodeURIComponent(id):'/dsh-dev-memory/state'}
function memoryToolCardModel(toolName,block){const args=blockArgs(block),out=blockOutput(block),done=!!(block&&'kind' in block),err=!!(block&&block.isError),state=!done?'running':err?'error':'ok',ws=out&&out.workspace||{};
 if(toolName==='memory_search'){const hits=out&&Array.isArray(out.results)?out.results:[];return{title:'查询项目记忆',state,query:args.query||'',count:hits.length,files:hits.map(x=>x.file||x.relPath).filter(Boolean),workspaceName:ws.name||ws.id||'',memoryRoot:ws.memoryRoot||'',summary:done?(hits.length+' 条命中'):(args.query||'查询中')} }
 if(toolName==='memory_write'){const audit=out&&out.audit||{},proposal=args.proposal||{},action=audit.action||(out&&out.written?'write':''),file=audit.relPath||proposal.draft&&proposal.draft.relPath||'',pres=actionPresentation(action);return{title:state==='running'?'写入项目记忆':pres.label+'项目记忆',state,action,file,summary:audit.summary||'',workspaceName:ws.name||ws.id||'',memoryRoot:ws.memoryRoot||'',module:audit.module||proposal.module||'',category:audit.category||proposal.category||'',confidence:audit.confidence||proposal.confidence||'',evidence:audit.evidenceSource||(Array.isArray(proposal.evidence)?proposal.evidence[0]:'')||'',ts:audit.ts} }
 const hs=out&&out.summary||{},sev=hs.severityCounts||{},issues=out&&out.issues||{},issueCount=Object.keys(issues).reduce((n,k)=>n+(Array.isArray(issues[k])?issues[k].length:0),0);return{title:'检查项目记忆',state,summary:(hs.markdownFiles||0)+' 个文件 · '+(sev.high||0)+' 高 / '+(sev.medium||0)+' 中 / '+(sev.low||0)+' 低',workspaceName:ws.name||ws.id||'',memoryRoot:ws.memoryRoot||'',directories:hs.directories||0,index:!!hs.memoryIndexExists,issueCount} }
function resultText(event){const content=event&&event.data&&event.data.message&&event.data.message.content;const first=Array.isArray(content)?content[0]:null;return first&&first.text||''}
const memoryWriteEventDefinition={kind:'dev-memory-writes',match(event){if(event.type==='turn/start')return{id:String(event.data.turn),role:'start'};if(event.type==='tool/call'||event.type==='tool/result')return{id:String(event.data.turn),role:'update'};return null},start(_c,match){return{turn:match.event.data.turn,calls:new Map(),writes:[]}},update(context,match){const state=context.state;if(match.event.type==='tool/call'){const calls=new Map(state.calls);calls.set(String(match.event.data.callId),match.event.data);return{...state,calls}}if(match.event.type!=='tool/result')return state;const message=match.event.data.message||{};if(message.content&&message.content[0]&&message.content[0].isError===true)return state;const callId=String(message.source&&message.source.callId||'');const call=state.calls.get(callId)||{};if(call.name!=='memory_write')return state;const out=parseJson(resultText(match.event))||{};if(!out||out.written!==true||!out.audit)return state;const write={seq:match.event.seq,action:out.audit.action||'write',relPath:out.audit.relPath,summary:out.audit.summary,workspace:out.workspace};if(state.writes.some(x=>x.seq===write.seq&&x.relPath===write.relPath))return state;return{...state,writes:[...state.writes,write]}}};
function selectMemoryWrites(owner){const raw=owner&&owner.turn&&owner.turn.data&&typeof owner.turn.data.get==='function'?owner.turn.data.get('dev-memory-writes')||owner.turn.data.get():null;const writes=(raw&&Array.isArray(raw.writes)?raw.writes:[]).filter(x=>!owner||owner.seq==null||x.seq==null||x.seq<=owner.seq);return writes.length?writes:null}
function readOwn(obj,key){try{const desc=Object.getOwnPropertyDescriptor(obj,key);return desc&&'value'in desc?desc.value:undefined}catch{return undefined}}
function readService(ctx,key,onError){if(!ctx)return undefined;if(typeof ctx.get==='function'){try{const value=ctx.get(key);if(value!==undefined)return value}catch(err){if(typeof onError==='function')onError(err)}}return readOwn(ctx,key)}

function createClientPlugin(React){
 const h=React&&React.createElement,useState=React&&React.useState,useEffect=React&&React.useEffect;
 const bootNotices=[];
 function remember(err,where){const message=err&&err.message?err.message:String(err||'');if(!message)return;bootNotices.push(where?where+': '+message:message)}
 function noticeNode(extra){const text=[...bootNotices,extra].filter(Boolean).join(' · ');return text?h('div',{className:'dm-feedback error','data-dev-memory':'boot-notice'},text):null}
 function StaticPanel(){return h?h('div',{'data-dev-memory':'review-panel',className:'dm-panel'},h('style',{},CSS),noticeNode(),h('div',{className:'dm-card'},'Dev Memory')):null}
 function LivePanel(){
  const [data,setData]=useState(null),[workspaces,setWorkspaces]=useState([]),[activeId,setActiveId]=useState(''),[browseId,setBrowseId]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[rootDraft,setRootDraft]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(null),[now,setNow]=useState(()=>Date.now()),[renameDraft,setRenameDraft]=useState(''),[showDiscovered,setShowDiscovered]=useState(false);
  function load(id){if(typeof fetch!=='function')return;const target=id==null?browseId:id;Promise.all([fetch('/dsh-dev-memory/workspaces',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('workspaces '+r.status))),fetch(browseStateUrl(target),{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('state '+r.status)))]).then(([ws,json])=>{setWorkspaces(ws&&ws.workspaces||[]);setActiveId(ws&&ws.activeWorkspaceId||'');setShowDiscovered(!!(ws&&ws.showDiscovered));setData(json);if(json&&json.config&&typeof json.config.memoryRoot==='string')setRootDraft(json.config.memoryRoot);setError('');setNow(Date.now())}).catch(e=>setError(e&&e.message?e.message:String(e)))}
  useEffect(()=>{load('');if(typeof setInterval!=='function')return;const id=setInterval(()=>load(),8000);return()=>clearInterval(id)},[]);
  function postConfig(body,text){if(typeof fetch!=='function')return;setBusy(true);setFeedback({tone:'',text:'保存中…'});fetch('/dsh-dev-memory/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.ok?r.json():Promise.reject(new Error('config '+r.status))).then(()=>{setFeedback({tone:'ok',text:'✓ '+(text||'已保存')});load()}).catch(e=>{const m=e&&e.message?e.message:String(e);setError(m);setFeedback({tone:'error',text:'保存失败：'+m})}).finally(()=>setBusy(false))}
  function postWorkspace(body,text){if(typeof fetch!=='function')return;setBusy(true);setFeedback({tone:'',text:'保存中…'});fetch('/dsh-dev-memory/workspaces',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.ok?r.json():Promise.reject(new Error('workspaces '+r.status))).then(()=>{setFeedback({tone:'ok',text:'✓ '+(text||'已保存')});if(body&&body.action==='remove'){setBrowseId('');load('')}else load()}).catch(e=>{const m=e&&e.message?e.message:String(e);setError(m);setFeedback({tone:'error',text:'保存失败：'+m})}).finally(()=>setBusy(false))}
  function choose(id){setBrowseId(id);load(id)}
  function openPath(path,text){if(!path||typeof fetch!=='function')return;setBusy(true);setFeedback({tone:'',text:'打开中…'});fetch('/dsh-dev-memory/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path})}).then(r=>r.ok?r.json():Promise.reject(new Error('open '+r.status))).then(()=>setFeedback({tone:'ok',text:'✓ '+(text||'已打开')})).catch(e=>{const m=e&&e.message?e.message:String(e);setError(m);setFeedback({tone:'error',text:'打开失败：'+m})}).finally(()=>setBusy(false))}
  const cfg=data&&data.config||{},audit=data&&Array.isArray(data.audit)?data.audit.slice().reverse():[],health=data&&data.health,hs=health&&health.summary||{},hi=health&&health.issues||{},sev=hs.severityCounts||{},issueKeys=Object.keys(hi).filter(k=>Array.isArray(hi[k])&&hi[k].length),waiting=cfg.rootMode==='auto-waiting',mode=waiting?'等待活跃会话工作区':cfg.rootMode==='auto'?'自动跟随会话工作区':'使用自定义目录';
  const merged=mergeWorkspaceRows(workspaces),visible=filterWorkspaces(merged,query),active=merged.find(x=>x.id===activeId),browsed=merged.find(x=>x.id===(data&&data.browseWorkspaceId||browseId))||active;
  const stat=(name,value)=>h('div',{className:'dm-stat'},h('div',{className:'dm-stat-name'},name),h('div',{className:'dm-stat-value'},String(value)));
  return h('div',{'data-dev-memory':'review-panel',className:'dm-panel'},h('style',{},CSS),
   noticeNode(data&&data.pluginError),
   h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot '+(activeId?'on':'warn')}),h('div',{},h('div',{className:'dm-title'},'记忆工作区'),h('div',{className:'dm-subtitle'},'选择器只改变浏览目标；从列表隐藏不会删除记忆目录'))),h('button',{className:'dm-button',disabled:busy,onClick:()=>load()},'↻ 刷新')),
    h('div',{className:'dm-grid'},
     h('div',{className:'dm-label'},'当前会话写入：'),h('div',{className:'dm-value'},active&&active.name||activeId||'等待会话绑定'),
     h('div',{className:'dm-label'},'当前面板浏览：'),h('div',{className:'dm-value'},(data&&data.browseWorkspace&&data.browseWorkspace.name)||browsed&&browsed.name||data&&data.browseWorkspaceId||'当前会话'),
     h('div',{className:'dm-label'},'浏览记忆目录：'),h('div',{className:'dm-value'},(data&&data.browseWorkspace&&data.browseWorkspace.memoryRoot)||(browsed&&browsed.memoryRoot)||'与当前会话相同')),
    h('input',{className:'dm-input',value:query,placeholder:'搜索工作区',onChange:e=>setQuery(e.target.value)}),h('div',{className:'dm-path-row',style:{marginTop:'8px'}},h('button',{className:'dm-button',disabled:busy,onClick:()=>postWorkspace({action:'showDiscovered',showDiscovered:!showDiscovered},showDiscovered?'已隐藏仅发现':'已显示仅发现')},showDiscovered?'隐藏仅发现':'显示仅发现')),
    h('div',{className:'dm-ws-list'},visible.map(row=>h('button',{key:row.id,className:'dm-ws-item'+(row.id===(data&&data.browseWorkspaceId||browseId||activeId)?' active':''),onClick:()=>choose(row.id)},h('div',{className:'dm-ws-name'},(row.pinned?'★ ':'')+row.name+' · '+workspaceStatusLabel(row,activeId)),h('div',{className:'dm-ws-path'},row.workspacePath||row.memoryRoot||row.id)))),
    browsed?h('div',{className:'dm-path-row',style:{marginTop:'8px'}},h('input',{className:'dm-input',value:renameDraft,placeholder:'自定义显示名称',onChange:e=>setRenameDraft(e.target.value)}),h('button',{className:'dm-button',disabled:busy||!renameDraft.trim(),onClick:()=>postWorkspace({action:'rename',id:browsed.id,name:renameDraft},'已重命名')},'重命名'),h('button',{className:'dm-button',disabled:busy,onClick:()=>postWorkspace({action:'pin',id:browsed.id,pinned:!browsed.pinned},browsed.pinned?'已取消置顶':'已置顶')},browsed.pinned?'取消置顶':'置顶'),h('button',{className:'dm-button',disabled:busy||!(browsed.workspacePath||(data&&data.browseWorkspace&&data.browseWorkspace.workspacePath)),onClick:()=>openPath((data&&data.browseWorkspace&&data.browseWorkspace.workspacePath)||browsed.workspacePath,'已打开工作目录')},'打开工作目录'),h('button',{className:'dm-button',disabled:busy||!((data&&data.browseWorkspace&&data.browseWorkspace.memoryRoot)||browsed.memoryRoot),onClick:()=>openPath((data&&data.browseWorkspace&&data.browseWorkspace.memoryRoot)||browsed.memoryRoot,'已打开记忆目录')},'打开记忆目录'),h('button',{className:'dm-button',disabled:busy,onClick:()=>postWorkspace({action:browsed.hidden?'unhide':'remove',id:browsed.id},browsed.hidden?'已取消隐藏':'已从列表隐藏')},browsed.hidden?'取消隐藏':'从列表隐藏')):null),
    h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot '+(waiting?'warn':(cfg.autoWrite!==false&&cfg.enabled!==false)?'on':'')}),h('div',{},h('div',{className:'dm-title'},'Dev Memory'),h('div',{className:'dm-subtitle'},(cfg.autoWrite!==false&&cfg.enabled!==false)?'新对话默认：自动更新已开 · '+mode:'新对话默认：仅开场查询 · '+mode))),h('label',{className:'dm-switch'},h('input',{type:'checkbox',checked:cfg.autoWrite!==false&&cfg.enabled!==false,disabled:busy,onChange:e=>postConfig({autoWrite:!!e.target.checked},e.target.checked?'已设为新对话默认开启':'已设为新对话默认关闭')}),h('span',{className:'dm-switch-track'}),h('span',{className:'dm-switch-knob'}))),
    h('div',{className:'dm-grid'},
     h('div',{className:'dm-label'},'工作目录：'),h('div',{className:'dm-value'},cfg.workspacePath||'等待会话绑定'),
     h('div',{className:'dm-label'},'记忆目录：'),h('div',{className:'dm-value'},h('div',{className:'dm-path-row'},h('input',{className:'dm-input',value:rootDraft,placeholder:waiting?'等待会话后自动生成':'',onChange:e=>{setRootDraft(e.target.value);setFeedback(null)}}),h('button',{className:'dm-button primary',disabled:busy||!rootDraft.trim(),onClick:()=>postConfig({memoryRoot:rootDraft},'路径已保存')},busy?'保存中…':'保存路径'),h('button',{className:'dm-button',disabled:busy||cfg.rootMode==='auto'||waiting,onClick:()=>postConfig({memoryRoot:''},'已恢复自动模式')},'恢复自动'))),
     h('div',{className:'dm-label'},'注入上限：'),h('div',{className:'dm-value'},String(cfg.maxInjectTokens==null?'':cfg.maxInjectTokens)+' tokens'),
     h('div',{className:'dm-label'},'最低置信度：'),h('div',{className:'dm-value'},String(cfg.writeConfidenceMin||'')),
     h('div',{className:'dm-label'},'自动写入等级：'),h('div',{className:'dm-value'},Array.isArray(cfg.autoWriteLevels)?cfg.autoWriteLevels.join('、'):'')),
    h('div',{className:'dm-feedback '+(feedback&&feedback.tone||'')},feedback?feedback.text:''),error?h('div',{className:'dm-feedback error'},error):null),
   h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot '+(health&&!health.error?'on':'warn')}),h('div',{},h('div',{className:'dm-title'},'健康状态'),h('div',{className:'dm-subtitle'},health&&!health.error?'记忆库已连接':'等待健康检查')))),
    health&&health.error?h('div',{className:'dm-empty'},health.error):h('div',{},h('div',{className:'dm-stat-row'},stat('目录',hs.directories||0),stat('记忆文件',hs.markdownFiles||0),stat('索引',hs.memoryIndexExists?'已生成':'未生成'),stat('问题（高/中/低）',(sev.high||0)+'/'+(sev.medium||0)+'/'+(sev.low||0))),issueKeys.length?h('div',{className:'dm-issues'},issueKeys.map(k=>h('div',{className:'dm-issue',key:k},h('div',{className:'dm-issue-title'},'⚠ '+(ISSUE_LABELS[k]||k)+'：'+hi[k].length),h('div',{className:'dm-issue-files'},hi[k].slice(0,4).map(formatIssueValue).join('、')+(hi[k].length>4?' …':''))))):h('div',{className:'dm-empty'},'✓ 未发现结构问题'))),
   h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot on'}),h('div',{},h('div',{className:'dm-title'},'最近变更'),h('div',{className:'dm-subtitle'},'写入日志、摘要与时间'))),h('button',{className:'dm-button',disabled:busy,onClick:()=>load()},'↻ 刷新')),
    audit.length?h('div',{className:'dm-changes'},audit.map((row,i)=>{const a=actionPresentation(row&&row.action),ts=row&&row.ts;return h('article',{className:'dm-change '+(i===0?'latest':''),key:String(ts||i)},h('div',{className:'dm-change-top'},h('span',{className:'dm-action '+a.tone},a.icon+' '+a.label),h('span',{className:'dm-file'},row&&row.relPath||row&&row.module||'未记录文件路径')),h('div',{className:'dm-summary'},row&&row.summary||'历史记录，无详细变更摘要'),h('div',{className:'dm-change-meta'},row&&row.module?h('span',{className:'dm-tag'},row.module):null,row&&row.category?h('span',{className:'dm-tag'},row.category):null,ts?h('span',{className:'change-time'},formatLocalTime(ts)+' · '+formatRelativeTime(ts,now)):null))})):h('div',{className:'dm-empty'},'暂无写入日志。完成一次记忆写入后会显示在这里。'))
  )
 }
 function MemoryToolRow({toolName,block,inspect}){const model=memoryToolCardModel(toolName,block);const details=[model.workspaceName&&('工作区：'+model.workspaceName),model.memoryRoot&&('记忆根：'+model.memoryRoot),model.query&&('查询：'+model.query),model.files&&model.files.length&&('文件：'+model.files.join('、')),model.file&&('文件：'+model.file),model.module&&('模块：'+model.module),model.category&&('分类：'+model.category),model.confidence&&('置信度：'+model.confidence),model.evidence&&('证据：'+model.evidence),model.ts&&('时间：'+formatLocalTime(model.ts)),toolName==='memory_health'&&model.directories!=null&&('目录：'+model.directories),toolName==='memory_health'&&('索引：'+(model.index?'已生成':'未生成')),toolName==='memory_health'&&model.issueCount!=null&&('问题：'+model.issueCount)].filter(Boolean);return h('details',{className:'dm-tool',open:model.state==='error'},h('summary',{onClick:inspect},model.title+' · '+(model.summary||model.file||'')),details.map((line,i)=>h('div',{className:'dm-summary',key:String(i)},line)))}
 function MemoryTurnTail(props){const writes=selectMemoryWrites(props)||props.match||[];if(!writes.length)return null;return h('div',{className:'dm-tail'},h('div',{className:'dm-title'},'记忆变更 · 本轮 '+writes.length+' 项'),writes.map((row,i)=>h('div',{key:String(row.seq||i)},actionPresentation(row.action).icon+' '+actionPresentation(row.action).label+' '+(row.relPath||''))))}
 function AutoWriteToggle(props){
   const sessionId=props&&(props.sessionId||(props.session&&props.session.id))||'';
   const [on,setOn]=useState(true),[busy,setBusy]=useState(false);
   function readOn(json){const row=json&&(json.session||json);if(row&&typeof row.autoWrite==='boolean')return row.autoWrite;const cfg=json&&json.config;return !cfg||(cfg.autoWrite!==false&&cfg.enabled!==false)}
   useEffect(()=>{if(typeof fetch!=='function'||!sessionId)return;fetch('/dsh-dev-memory/session-auto-write?sessionId='+encodeURIComponent(sessionId),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(json=>{if(json)setOn(readOn(json))}).catch(()=>{})},[sessionId]);
   function toggle(next){if(typeof fetch!=='function'||!sessionId){setOn(next);return}setBusy(true);setOn(next);fetch('/dsh-dev-memory/session-auto-write',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:sessionId,autoWrite:next})}).then(r=>r.ok?r.json():Promise.reject(new Error('session-auto-write '+r.status))).then(json=>{if(json)setOn(readOn(json))}).catch(()=>setOn(!next)).finally(()=>setBusy(false))}
   return h('label',{'data-dev-memory':'auto-write-toggle',className:'dm-composer-toggle',title:'只改当前对话。关闭后仍在会话开始查询记忆，但不再自动提醒写盘'},h('style',{},CSS),h('span',{},'自动记忆'),h('span',{className:'dm-switch'},h('input',{type:'checkbox',checked:!!on,disabled:busy||!sessionId,onChange:e=>toggle(!!e.target.checked)}),h('span',{className:'dm-switch-track'}),h('span',{className:'dm-switch-knob'})))
  }
  function WritePassDock(props){
   const sessionId=props&&(props.sessionId||(props.session&&props.session.id))||'';
   const [active,setActive]=useState(false),[busy,setBusy]=useState(false);
   function readActive(json){const row=json&&(json.session||json);return !!(row&&row.writePass&&row.writePass.active)}
   useEffect(()=>{if(typeof fetch!=='function'||!sessionId)return;function load(){fetch('/dsh-dev-memory/session-auto-write?sessionId='+encodeURIComponent(sessionId),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(json=>{if(json)setActive(readActive(json))}).catch(()=>{})}load();if(typeof setInterval!=='function')return;const id=setInterval(load,1500);return()=>clearInterval(id)},[sessionId]);
   function stop(){if(typeof fetch!=='function'||!sessionId){setActive(false);return}setBusy(true);fetch('/dsh-dev-memory/session-auto-write',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:sessionId,action:'stopWritePass'})}).then(r=>r.ok?r.json():Promise.reject(new Error('stopWritePass '+r.status))).then(json=>{setActive(readActive(json))}).catch(()=>{}).finally(()=>setBusy(false))}
   if(!active)return null;
   return h('div',{'data-dev-memory':'write-pass-dock',className:'dm-writepass'},h('style',{},CSS),h('span',{},'正在写入记忆'),h('button',{className:'dm-button',disabled:busy||!sessionId,onClick:stop},'停止'))
  }
  const Panel=useState&&useEffect?LivePanel:StaticPanel;
 const Toggle=useState&&useEffect?AutoWriteToggle:function StaticToggle(){return h?h('label',{'data-dev-memory':'auto-write-toggle',className:'dm-composer-toggle'},'自动记忆'):null};const Dock=useState&&useEffect?WritePassDock:function StaticDock(){return null};
 return{name:'dsh-dev-memory',inject:['slots'],apply(ctx){try{const slots=readService(ctx,'slots',err=>remember(err,'slots'));if(!slots||typeof slots.inject!=='function'||typeof slots.register!=='function')return;try{slots.inject('settings.section',()=>slots.register({name:'settings.section',id:'dev-memory',order:100,label:'dev-memory'},Panel))}catch(err){remember(err,'settings');return}try{slots.inject('conversation.input.left',()=>slots.register({name:'conversation.input.left',id:'dev-memory-auto-write',order:20,label:'自动记忆'},Toggle))}catch(err){remember(err,'input')}try{slots.inject('conversation.input.dock',()=>slots.register({name:'conversation.input.dock',id:'dev-memory-write-pass',order:15,label:'正在写入记忆'},Dock))}catch(err){remember(err,'dock')}try{['memory_search','memory_write','memory_health'].forEach(key=>slots.inject('tool.call.toolview',()=>slots.register({name:'tool.call.toolview',key},MemoryToolRow)))}catch(err){remember(err,'toolview')}try{const events=readService(ctx,'conversationEvents',err=>remember(err,'conversationEvents'));if(events&&typeof events.register==='function'){events.register(memoryWriteEventDefinition);slots.inject('conversation.chat.turnTail',()=>slots.register({name:'conversation.chat.turnTail',select:selectMemoryWrites},MemoryTurnTail))}}catch(err){remember(err,'conversationEvents')}}catch(err){remember(err,'apply')}}}
}
if(typeof window!=='undefined'&&window.__ModuleLoader__)window.__ModuleLoader__.load({id:'dsh-dev-memory',factory:require=>{let React;try{React=require('react')}catch{React=undefined}return createClientPlugin(React)}});
if(typeof module!=='undefined'&&module.exports)module.exports={createClientPlugin,formatIssueValue,actionPresentation,formatLocalTime,formatRelativeTime,filterWorkspaces,mergeWorkspaceRows,workspaceStatusLabel,browseStateUrl,memoryToolCardModel,memoryWriteEventDefinition,selectMemoryWrites,default:createClientPlugin};
