/** dsh-dev-memory polished settings panel — static CJS client bundle. */
const CSS = [
'.dm-panel{padding:16px;line-height:1.5;color:inherit}',
'.dm-card{border:1px solid var(--dsw-alias-border-primary,rgba(127,127,127,.22));border-radius:14px;padding:16px;margin-bottom:14px;background:var(--dsw-alias-bg-secondary,rgba(127,127,127,.045));box-shadow:0 1px 2px rgba(0,0,0,.04)}',
'.dm-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}',
'.dm-title-wrap{display:flex;align-items:center;gap:9px;min-width:0}.dm-title{font-size:15px;font-weight:700}.dm-subtitle{font-size:12px;color:var(--dsw-alias-label-secondary,#888)}',
'.dm-status-dot{width:9px;height:9px;border-radius:50%;background:#999;box-shadow:0 0 0 3px rgba(127,127,127,.12);flex:none}.dm-status-dot.on{background:#21c765;box-shadow:0 0 0 3px rgba(33,199,101,.14)}.dm-status-dot.warn{background:#f1a72c;box-shadow:0 0 0 3px rgba(241,167,44,.14)}',
'.dm-grid{display:grid;grid-template-columns:minmax(112px,145px) minmax(0,1fr);gap:9px 12px;align-items:start}.dm-label{font-size:12px;font-weight:700;color:var(--dsw-alias-label-secondary,#777)}.dm-value{font-size:13px;min-width:0;word-break:break-all}',
'.dm-path-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.dm-input{flex:1;min-width:210px;padding:7px 10px;border:1px solid var(--dsw-alias-border-primary,#aaa);border-radius:7px;background:var(--dsw-alias-bg-primary,transparent);color:inherit;outline:none;transition:border-color .15s,box-shadow .15s}.dm-input:focus{border-color:#3c8cff;box-shadow:0 0 0 3px rgba(60,140,255,.14)}',
'.dm-button{appearance:none;border:1px solid var(--dsw-alias-border-primary,#aaa);border-radius:8px;padding:6px 12px;background:var(--dsw-alias-bg-primary,transparent);color:inherit;font-size:12px;font-weight:600;cursor:pointer;transition:background .14s,border-color .14s,transform .08s,box-shadow .14s}.dm-button:hover:not(:disabled){background:rgba(60,140,255,.1);border-color:#3c8cff;box-shadow:0 2px 8px rgba(0,0,0,.08)}.dm-button:active:not(:disabled){transform:scale(.96);box-shadow:none}.dm-button:disabled{opacity:.48;cursor:not-allowed}.dm-button.primary{background:#287be6;border-color:#287be6;color:#fff}',
'.dm-feedback{font-size:12px;font-weight:600;min-height:18px;margin-top:8px}.dm-feedback.ok{color:#159b4b}.dm-feedback.error{color:#d34b4b}',
'.dm-switch{position:relative;display:inline-flex;width:38px;height:22px;cursor:pointer;flex:none}.dm-switch input{position:absolute;opacity:0}.dm-switch-track{position:absolute;inset:0;border-radius:99px;background:#aaa;transition:.18s}.dm-switch-knob{position:absolute;width:18px;height:18px;left:2px;top:2px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.28);transition:transform .18s}.dm-switch input:checked~.dm-switch-track{background:#20bd61}.dm-switch input:checked~.dm-switch-knob{transform:translateX(16px)}.dm-switch:hover .dm-switch-track{box-shadow:0 0 0 3px rgba(33,199,101,.12)}',
'.dm-stat-row{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:11px}.dm-stat{padding:9px 10px;border-radius:9px;background:rgba(127,127,127,.075)}.dm-stat-name{font-size:11px;color:var(--dsw-alias-label-secondary,#888)}.dm-stat-value{font-size:15px;font-weight:700}',
'.dm-issues,.dm-changes{display:flex;flex-direction:column;gap:8px}.dm-issue{padding:9px 10px;border-left:3px solid #e4a02a;border-radius:6px;background:rgba(228,160,42,.075)}.dm-issue-title{font-size:12px;font-weight:700}.dm-issue-files,.dm-empty{font-size:11px;color:var(--dsw-alias-label-secondary,#888);margin-top:3px;word-break:break-word}',
'.dm-change{padding:11px 12px 11px 14px;border:1px solid var(--dsw-alias-border-primary,rgba(127,127,127,.18));border-radius:10px;background:var(--dsw-alias-bg-primary,transparent)}.dm-change.latest{border-left:4px solid #21c765;background:rgba(33,199,101,.045)}.dm-change-top,.dm-change-meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.dm-action{font-size:11px;font-weight:700;padding:2px 7px;border-radius:99px}.dm-action.create{color:#128b43;background:rgba(33,199,101,.13)}.dm-action.update{color:#2673d6;background:rgba(60,140,255,.13)}.dm-action.write{color:inherit;background:rgba(127,127,127,.12)}.dm-file{font-size:12px;font-weight:700;word-break:break-all}.dm-summary{font-size:12px;margin-top:5px}.dm-change-meta{margin-top:6px;font-size:11px;color:var(--dsw-alias-label-secondary,#888)}.dm-tag{padding:1px 6px;border-radius:99px;background:rgba(127,127,127,.1)}.change-time{font-variant-numeric:tabular-nums}',
'@media(max-width:640px){.dm-grid{grid-template-columns:1fr}.dm-stat-row{grid-template-columns:repeat(2,minmax(0,1fr))}.dm-input{min-width:160px}}'
].join('');

const ISSUE_LABELS={missingReadmeDirs:'缺少目录索引',overlongFiles:'文件过长',missingMeta:'缺少元数据',missingQuickJudgment:'缺少快速判断',missingAssociatedMemory:'缺少关联记忆',missingPendingVerification:'缺少待验证项',oldLineTables:'旧格式行号表',pendingEntrypoints:'待补入口',brokenLinks:'失效链接',duplicateLinks:'重复链接',sameNameMdAndDir:'文档与目录重名',bomFiles:'BOM 文件',replacementCharFiles:'异常替换字符'};
function formatIssueValue(v){if(v==null)return'';if(typeof v!=='object')return String(v);const p=v.file||v.path||v.relPath||v.dir||v.module||'';const d=v.meta||v.reason||v.message||v.issue||'';if(p&&d)return String(p)+' — '+String(d);if(p||d)return String(p||d);try{return JSON.stringify(v)}catch{return String(v)}}
function actionPresentation(a){if(a==='create')return{icon:'+',label:'新增',tone:'create'};if(a==='update')return{icon:'✎',label:'更新',tone:'update'};return{icon:'•',label:'写入',tone:'write'}}
function pad2(v){return String(v).padStart(2,'0')}
function formatLocalTime(ts,offset){const n=Number(ts);if(!Number.isFinite(n))return'';const x=Number.isFinite(offset),d=new Date(x?n-offset*60000:n);const g=x?'getUTC':'get';return d[g+'FullYear']()+'-'+pad2(d[g+'Month']()+1)+'-'+pad2(d[g+'Date']())+' '+pad2(d[g+'Hours']())+':'+pad2(d[g+'Minutes']())+':'+pad2(d[g+'Seconds']())}
function formatRelativeTime(ts,now){const diff=Math.max(0,Number(now==null?Date.now():now)-Number(ts));if(!Number.isFinite(diff)||diff<60000)return'刚刚';const m=Math.floor(diff/60000);if(m<60)return m+' 分钟前';const h=Math.floor(m/60);if(h<24)return h+' 小时前';return Math.floor(h/24)+' 天前'}

function createClientPlugin(React){
 const h=React&&React.createElement,useState=React&&React.useState,useEffect=React&&React.useEffect;
 function StaticPanel(){return h?h('div',{'data-dev-memory':'review-panel',className:'dm-panel'},h('style',{},CSS),h('div',{className:'dm-card'},'Dev Memory')):null}
 function LivePanel(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[rootDraft,setRootDraft]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(null),[now,setNow]=useState(()=>Date.now());
  function load(){if(typeof fetch!=='function')return;fetch('/dsh-dev-memory/state',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('state '+r.status))).then(json=>{setData(json);if(json&&json.config&&typeof json.config.memoryRoot==='string')setRootDraft(json.config.memoryRoot);setError('');setNow(Date.now())}).catch(e=>setError(e&&e.message?e.message:String(e)))}
  useEffect(()=>{load();if(typeof setInterval!=='function')return;const id=setInterval(load,8000);return()=>clearInterval(id)},[]);
  function postConfig(body,text){if(typeof fetch!=='function')return;setBusy(true);setFeedback({tone:'',text:'保存中…'});fetch('/dsh-dev-memory/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.ok?r.json():Promise.reject(new Error('config '+r.status))).then(()=>{setFeedback({tone:'ok',text:'✓ '+(text||'已保存')});load()}).catch(e=>{const m=e&&e.message?e.message:String(e);setError(m);setFeedback({tone:'error',text:'保存失败：'+m})}).finally(()=>setBusy(false))}
  const cfg=data&&data.config||{},audit=data&&Array.isArray(data.audit)?data.audit.slice().reverse():[],health=data&&data.health,hs=health&&health.summary||{},hi=health&&health.issues||{},sev=hs.severityCounts||{},issueKeys=Object.keys(hi).filter(k=>Array.isArray(hi[k])&&hi[k].length),waiting=cfg.rootMode==='auto-waiting',mode=waiting?'等待活跃会话工作区':cfg.rootMode==='auto'?'自动跟随会话工作区':'使用自定义目录';
  const stat=(name,value)=>h('div',{className:'dm-stat'},h('div',{className:'dm-stat-name'},name),h('div',{className:'dm-stat-value'},String(value)));
  return h('div',{'data-dev-memory':'review-panel',className:'dm-panel'},h('style',{},CSS),
   h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot '+(waiting?'warn':cfg.enabled?'on':'')}),h('div',{},h('div',{className:'dm-title'},'Dev Memory'),h('div',{className:'dm-subtitle'},cfg.enabled?'已启用 · '+mode:'已停用'))),h('label',{className:'dm-switch'},h('input',{type:'checkbox',checked:!!cfg.enabled,disabled:busy,onChange:e=>postConfig({enabled:!!e.target.checked},e.target.checked?'已启用':'已停用')}),h('span',{className:'dm-switch-track'}),h('span',{className:'dm-switch-knob'}))),
    h('div',{className:'dm-grid'},
     h('div',{className:'dm-label'},'工作目录：'),h('div',{className:'dm-value'},cfg.workspacePath||'等待会话绑定'),
     h('div',{className:'dm-label'},'记忆目录：'),h('div',{className:'dm-value'},h('div',{className:'dm-path-row'},h('input',{className:'dm-input',value:rootDraft,placeholder:waiting?'等待会话后自动生成':'',onChange:e=>{setRootDraft(e.target.value);setFeedback(null)}}),h('button',{className:'dm-button primary',disabled:busy||!rootDraft.trim(),onClick:()=>postConfig({memoryRoot:rootDraft},'路径已保存')},busy?'保存中…':'保存路径'),h('button',{className:'dm-button',disabled:busy||cfg.rootMode==='auto'||waiting,onClick:()=>postConfig({memoryRoot:''},'已恢复自动模式')},'恢复自动'))),
     h('div',{className:'dm-label'},'注入上限：'),h('div',{className:'dm-value'},String(cfg.maxInjectTokens==null?'':cfg.maxInjectTokens)+' tokens'),
     h('div',{className:'dm-label'},'最低置信度：'),h('div',{className:'dm-value'},String(cfg.writeConfidenceMin||'')),
     h('div',{className:'dm-label'},'自动写入等级：'),h('div',{className:'dm-value'},Array.isArray(cfg.autoWriteLevels)?cfg.autoWriteLevels.join('、'):'')),
    h('div',{className:'dm-feedback '+(feedback&&feedback.tone||'')},feedback?feedback.text:''),error?h('div',{className:'dm-feedback error'},error):null),
   h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot '+(health&&!health.error?'on':'warn')}),h('div',{},h('div',{className:'dm-title'},'健康状态'),h('div',{className:'dm-subtitle'},health&&!health.error?'记忆库已连接':'等待健康检查')))),
    health&&health.error?h('div',{className:'dm-empty'},health.error):h('div',{},h('div',{className:'dm-stat-row'},stat('目录',hs.directories||0),stat('记忆文件',hs.markdownFiles||0),stat('索引',hs.memoryIndexExists?'已生成':'未生成'),stat('问题（高/中/低）',(sev.high||0)+'/'+(sev.medium||0)+'/'+(sev.low||0))),issueKeys.length?h('div',{className:'dm-issues'},issueKeys.map(k=>h('div',{className:'dm-issue',key:k},h('div',{className:'dm-issue-title'},'⚠ '+(ISSUE_LABELS[k]||k)+'：'+hi[k].length),h('div',{className:'dm-issue-files'},hi[k].slice(0,4).map(formatIssueValue).join('、')+(hi[k].length>4?' …':''))))):h('div',{className:'dm-empty'},'✓ 未发现结构问题'))),
   h('section',{className:'dm-card'},
    h('div',{className:'dm-card-head'},h('div',{className:'dm-title-wrap'},h('span',{className:'dm-status-dot on'}),h('div',{},h('div',{className:'dm-title'},'最近变更'),h('div',{className:'dm-subtitle'},'写入日志、摘要与时间'))),h('button',{className:'dm-button',disabled:busy,onClick:load},'↻ 刷新')),
    audit.length?h('div',{className:'dm-changes'},audit.map((row,i)=>{const a=actionPresentation(row&&row.action),ts=row&&row.ts;return h('article',{className:'dm-change '+(i===0?'latest':''),key:String(ts||i)},h('div',{className:'dm-change-top'},h('span',{className:'dm-action '+a.tone},a.icon+' '+a.label),h('span',{className:'dm-file'},row&&row.relPath||row&&row.module||'未记录文件路径')),h('div',{className:'dm-summary'},row&&row.summary||'历史记录，无详细变更摘要'),h('div',{className:'dm-change-meta'},row&&row.module?h('span',{className:'dm-tag'},row.module):null,row&&row.category?h('span',{className:'dm-tag'},row.category):null,ts?h('span',{className:'change-time'},formatLocalTime(ts)+' · '+formatRelativeTime(ts,now)):null))})):h('div',{className:'dm-empty'},'暂无写入日志。完成一次记忆写入后会显示在这里。'))
  )
 }
 const Panel=useState&&useEffect?LivePanel:StaticPanel;
 return{name:'dsh-dev-memory',inject:['slots'],apply(ctx){const slots=ctx&&ctx.slots||ctx&&typeof ctx.get==='function'&&ctx.get('slots');if(!slots||typeof slots.inject!=='function'||typeof slots.register!=='function')return;slots.inject('settings.section',()=>slots.register({name:'settings.section',id:'dev-memory',order:100,label:'dev-memory'},Panel))}}
}
if(typeof window!=='undefined'&&window.__ModuleLoader__)window.__ModuleLoader__.load({id:'dsh-dev-memory',factory:require=>{let React;try{React=require('react')}catch{React=undefined}return createClientPlugin(React)}});
if(typeof module!=='undefined'&&module.exports)module.exports={createClientPlugin,formatIssueValue,actionPresentation,formatLocalTime,formatRelativeTime,default:createClientPlugin};
